#ifndef CML_ALL
#define CML_ALL

#include "ModelUpdate.h"
#include "Alphabet.h"
#include "NRMat.h"
#include "UniOP.h"
#include "BiOP.h"
#include "TriOP.h"
#include "FourOP.h"
#include "MyLib.h"
#include "LookupTable.h"
#include "SoftMaxLoss.h"
#include "CheckGrad.h"
#include "SparseOP.h"
#include "APOP.h"
#include "Pooling.h"
#include "Metric.h"
#include "Windowlized.h"
#include "Concat.h"
#include "Node.h"
#include "Graph.h"
#include "CRFMLLoss.h"
#include "Semi0CRFMLLoss.h"
#include "SemiCRFMLLoss.h"
#include "LSTM.h"
#include "LSTM1.h"
#include "AtomicOP.h"
#include "APCOP.h"
#include "SparseCOP.h"
#include "COPUtils.h"
#include "RNN.h"
#include "GRNN.h"
#include "MyTensor.h"


#endif
